apiVersion: apps/v1
kind: Deployment
metadata:
  name: okteto-poc
spec:
  selector:
    matchLabels:
      app: okteto-poc
  replicas: 1
  template:
    metadata:
      labels:
        app: okteto-poc
    spec:
      containers:
      - name: okteto-poc
        image: okteto.dev/okteto-poc:latest
        ports:
        - containerPort: 3000