apiVersion: v1
kind: Service
metadata:
  name: okteto-poc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 1234
      protocol: TCP
  selector:
    app: okteto-poc